// SPDX-License-Identifier: GPL-2.0
/*
 * Serial driver for the NEC PC-9800 internal uPD8251 USART, targeting the
 * NP2kai emulator. Registers as ttyS0 and doubles as the console.
 *
 * The device is not 8250-compatible: data at I/O 0x30, mode/command/status at
 * 0x32, and its baud rate is generated by 8253 counter 2 (control 0x77, data
 * 0x75). RX interrupts would need the PC-98 sysport (0x35) and PIC gating; to
 * keep bring-up simple and robust this driver polls RX with a timer instead.
 *
 * NP2kai quirk this driver copes with: its TxRDY status bit drops after the
 * first transmitted byte and never returns (a write-success polarity bug in
 * the emulator's pty backend), yet the byte still reaches the host. TX pings
 * TxRDY with a bounded wait (correct pacing on real hardware, which has no TX
 * FIFO); the first timeout latches polling off so NP2kai then writes blind.
 * RX polling only works once 8253 ch2 has been programmed (that arms the
 * emulator's receive pump), which set_termios does via the baud divisor.
 */
#include <linux/console.h>
#include <linux/init.h>
#include <linux/io.h>
#include <linux/module.h>
#include <linux/platform_device.h>
#include <linux/serial_core.h>
#include <linux/timer.h>
#include <linux/timex.h>
#include <linux/tty.h>
#include <linux/tty_flip.h>

#define PC98_SIO_DATA		0x30	/* R: RxD  W: TxD */
#define PC98_SIO_CMD		0x32	/* R: status  W: mode/command */
#define PC98_SIO_SYSPORT	0x35	/* interrupt-enable bits (unused: polled) */

#define PC98_PIT_CH2		0x75	/* 8253 counter 2 data (baud divisor) */
#define PC98_PIT_CTRL		0x77	/* 8253 control word */

/* status bits (read 0x32) */
#define ST_TXRDY		0x01
#define ST_RXRDY		0x02
#define ST_TXEMPTY		0x04

/* command bits (write 0x32, case 2) */
#define CMD_TXEN		0x01
#define CMD_DTR			0x02
#define CMD_RXEN		0x04
#define CMD_ERRRST		0x10
#define CMD_RTS			0x20

/* The baud generator is 8253 counter 2, so it runs off the PIT's input clock —
 * which is 2.4576 MHz or 1.9968 MHz depending on the machine family. */
#define PC98_UARTCLK		PIT_TICK_RATE
#define POLL_INTERVAL_MS	5

static struct uart_port pc98_port;
static struct timer_list pc98_rx_timer;

static void pc98_8251_program_baud(unsigned int baud)
{
	/* 8253 ch2 as baud generator, x16 sampling: divisor = clk / (16*baud).
	 * Writing the full 16-bit count to 0x75 is what arms NP2kai's serial
	 * receive/transmit pump; without it RX never happens. */
	unsigned int div = PC98_UARTCLK / (16 * (baud ? baud : 9600));

	if (!div)
		div = 1;
	outb(0xb6, PC98_PIT_CTRL);		/* ch2, mode3, 16-bit, binary */
	outb(div & 0xff, PC98_PIT_CH2);
	outb((div >> 8) & 0xff, PC98_PIT_CH2);
}

static void pc98_8251_init_chip(void)
{
	/* uPD8251 reset dance: three dummy writes, internal reset, mode, cmd. */
	outb(0x00, PC98_SIO_CMD);
	outb(0x00, PC98_SIO_CMD);
	outb(0x00, PC98_SIO_CMD);
	outb(0x40, PC98_SIO_CMD);			/* internal reset */
	outb(0x4e, PC98_SIO_CMD);			/* mode: async x16, 8N1 */
	outb(CMD_TXEN | CMD_RXEN | CMD_DTR | CMD_RTS | CMD_ERRRST,
	     PC98_SIO_CMD);				/* command */
}

/*
 * Wait for TxRDY before loading the next byte. Real hardware needs this pacing
 * (the uPD8251 has no TX FIFO; writing while busy drops the byte). NP2kai's
 * TxRDY is stuck low after the first byte (write-success polarity bug), so the
 * poll would never return there — the first timeout latches it off and every
 * later byte goes out blind, which is what NP2kai wants anyway.
 */
static bool pc98_tx_poll_ok = true;

static void pc98_8251_tx_wait(void)
{
	unsigned int timeout = 200000;

	if (!pc98_tx_poll_ok)
		return;
	while (!(inb(PC98_SIO_CMD) & ST_TXRDY)) {
		if (!--timeout) {
			pc98_tx_poll_ok = false;	/* broken (NP2kai): go blind */
			return;
		}
		cpu_relax();
	}
}

/* ---- uart_ops ---- */

static unsigned int pc98_8251_tx_empty(struct uart_port *port)
{
	if (pc98_tx_poll_ok)
		return (inb(PC98_SIO_CMD) & ST_TXEMPTY) ? TIOCSER_TEMT : 0;
	return TIOCSER_TEMT;	/* NP2kai: TxEMPTY unusable, claim drained */
}

static void pc98_8251_set_mctrl(struct uart_port *port, unsigned int mctrl)
{
}

static unsigned int pc98_8251_get_mctrl(struct uart_port *port)
{
	return TIOCM_CTS | TIOCM_DSR | TIOCM_CAR;
}

static void pc98_8251_stop_tx(struct uart_port *port)
{
}

static void pc98_8251_tx_chars(struct uart_port *port)
{
	u8 ch;

	/* Pace on TxRDY when it works (real HW); blind on NP2kai (see tx_wait). */
	uart_port_tx(port, ch, true,
		     ({ pc98_8251_tx_wait(); outb(ch, PC98_SIO_DATA); }));
}

static void pc98_8251_start_tx(struct uart_port *port)
{
	pc98_8251_tx_chars(port);
}

static void pc98_8251_stop_rx(struct uart_port *port)
{
}

static void pc98_8251_rx_poll(struct timer_list *t)
{
	struct uart_port *port = &pc98_port;
	unsigned long flags;
	int pushed = 0;

	uart_port_lock_irqsave(port, &flags);
	while (inb(PC98_SIO_CMD) & ST_RXRDY) {
		u8 ch = inb(PC98_SIO_DATA);

		port->icount.rx++;
		if (!uart_handle_sysrq_char(port, ch))
			uart_insert_char(port, 0, 0, ch, TTY_NORMAL);
		pushed = 1;
	}
	uart_port_unlock_irqrestore(port, flags);

	if (pushed)
		tty_flip_buffer_push(&port->state->port);

	mod_timer(&pc98_rx_timer, jiffies + msecs_to_jiffies(POLL_INTERVAL_MS));
}

static int pc98_8251_startup(struct uart_port *port)
{
	pc98_8251_init_chip();
	pc98_8251_program_baud(9600);
	timer_setup(&pc98_rx_timer, pc98_8251_rx_poll, 0);
	mod_timer(&pc98_rx_timer, jiffies + msecs_to_jiffies(POLL_INTERVAL_MS));
	return 0;
}

static void pc98_8251_shutdown(struct uart_port *port)
{
	del_timer_sync(&pc98_rx_timer);
}

static void pc98_8251_set_termios(struct uart_port *port,
				  struct ktermios *new,
				  const struct ktermios *old)
{
	unsigned int baud = uart_get_baud_rate(port, new, old, 1200, 38400);

	pc98_8251_program_baud(baud);
	uart_update_timeout(port, new->c_cflag, baud);
}

static const char *pc98_8251_type(struct uart_port *port)
{
	return "uPD8251";
}

static void pc98_8251_config_port(struct uart_port *port, int flags)
{
	if (flags & UART_CONFIG_TYPE)
		port->type = PORT_8250;	/* any non-PORT_UNKNOWN sentinel */
}

static int pc98_8251_verify_port(struct uart_port *port,
				 struct serial_struct *ser)
{
	return 0;
}

static void pc98_8251_release_port(struct uart_port *port)
{
}

static int pc98_8251_request_port(struct uart_port *port)
{
	return 0;
}

static const struct uart_ops pc98_8251_ops = {
	.tx_empty	= pc98_8251_tx_empty,
	.set_mctrl	= pc98_8251_set_mctrl,
	.get_mctrl	= pc98_8251_get_mctrl,
	.stop_tx	= pc98_8251_stop_tx,
	.start_tx	= pc98_8251_start_tx,
	.stop_rx	= pc98_8251_stop_rx,
	.startup	= pc98_8251_startup,
	.shutdown	= pc98_8251_shutdown,
	.set_termios	= pc98_8251_set_termios,
	.type		= pc98_8251_type,
	.config_port	= pc98_8251_config_port,
	.verify_port	= pc98_8251_verify_port,
	.release_port	= pc98_8251_release_port,
	.request_port	= pc98_8251_request_port,
};

/* ---- console ---- */

#ifdef CONFIG_SERIAL_PC98_8251_CONSOLE

static void pc98_8251_console_putchar(struct uart_port *port, unsigned char c)
{
	if (c == '\n') {
		pc98_8251_tx_wait();
		outb('\r', PC98_SIO_DATA);
	}
	pc98_8251_tx_wait();
	outb(c, PC98_SIO_DATA);
}

static void pc98_8251_console_write(struct console *co, const char *s,
				    unsigned int count)
{
	uart_console_write(&pc98_port, s, count, pc98_8251_console_putchar);
}

static int __init pc98_8251_console_setup(struct console *co, char *options)
{
	int baud = 9600, bits = 8, parity = 'n', flow = 'n';

	pc98_port.iobase = PC98_SIO_DATA;
	pc98_port.iotype = UPIO_PORT;
	pc98_port.uartclk = PC98_UARTCLK;
	pc98_port.ops = &pc98_8251_ops;
	pc98_port.line = 0;

	pc98_8251_init_chip();

	if (options)
		uart_parse_options(options, &baud, &parity, &bits, &flow);
	pc98_8251_program_baud(baud);
	return uart_set_options(&pc98_port, co, baud, parity, bits, flow);
}

static struct uart_driver pc98_8251_reg;

static struct console pc98_8251_console = {
	.name	= "ttyS",
	.write	= pc98_8251_console_write,
	.device	= uart_console_device,
	.setup	= pc98_8251_console_setup,
	.flags	= CON_PRINTBUFFER,
	.index	= -1,
	.data	= &pc98_8251_reg,
};

static int __init pc98_8251_console_init(void)
{
	register_console(&pc98_8251_console);
	return 0;
}
console_initcall(pc98_8251_console_init);

#define PC98_8251_CONSOLE	(&pc98_8251_console)
#else
#define PC98_8251_CONSOLE	NULL
#endif

static struct uart_driver pc98_8251_reg = {
	.owner		= THIS_MODULE,
	.driver_name	= "pc98_8251",
	.dev_name	= "ttyS",
	.major		= TTY_MAJOR,
	.minor		= 64,
	.nr		= 1,
	.cons		= PC98_8251_CONSOLE,
};

static struct platform_device *pc98_8251_pdev;

static int __init pc98_8251_init(void)
{
	int ret;

	ret = uart_register_driver(&pc98_8251_reg);
	if (ret)
		return ret;

	pc98_8251_pdev = platform_device_register_simple("pc98_8251", -1,
							  NULL, 0);
	if (IS_ERR(pc98_8251_pdev)) {
		ret = PTR_ERR(pc98_8251_pdev);
		goto err_driver;
	}

	pc98_port.iobase	= PC98_SIO_DATA;
	pc98_port.iotype	= UPIO_PORT;
	pc98_port.irq		= 0;		/* polled */
	pc98_port.uartclk	= PC98_UARTCLK;
	pc98_port.fifosize	= 1;
	pc98_port.flags		= UPF_BOOT_AUTOCONF;
	pc98_port.ops		= &pc98_8251_ops;
	pc98_port.line		= 0;
	pc98_port.type		= PORT_UNKNOWN;
	pc98_port.dev		= &pc98_8251_pdev->dev;

	ret = uart_add_one_port(&pc98_8251_reg, &pc98_port);
	if (ret)
		goto err_pdev;

	return 0;

err_pdev:
	platform_device_unregister(pc98_8251_pdev);
err_driver:
	uart_unregister_driver(&pc98_8251_reg);
	return ret;
}

static void __exit pc98_8251_exit(void)
{
	uart_remove_one_port(&pc98_8251_reg, &pc98_port);
	platform_device_unregister(pc98_8251_pdev);
	uart_unregister_driver(&pc98_8251_reg);
}

module_init(pc98_8251_init);
module_exit(pc98_8251_exit);

MODULE_DESCRIPTION("NEC PC-9800 uPD8251 serial driver");
MODULE_LICENSE("GPL");
